DROP TABLE IF EXISTS auth_code;
DROP TABLE IF EXISTS member_detail;
DROP TABLE IF EXISTS member_quit;
DROP TABLE IF EXISTS member;

create table auth_code (
                           id bigint generated by default as identity,
                           member_id bigint,
                           auth_cnt integer,
                           auth_code varchar(255),
                           auth_method_code varchar(255),
                           is_auth_success varchar(255),
                           created_dt timestamp,
                           updated_dt timestamp,
                           primary key (id)
);
create table member (
                        id bigint generated by default as identity,
                        access_token varchar(255),
                        device_type varchar(255),
                        dormant_apply_dt timestamp,
                        email_receive_dt timestamp,
                        is_email_receive varchar(255),
                        is_pwd_init varchar(255),
                        is_sms_receive varchar(255),
                        join_path_code varchar(255),
                        last_login_dt timestamp,
                        login_fail_cnt integer,
                        login_ip varchar(255),
                        nickname varchar(255),
                        password varchar(255),
                        pwd_change_dt timestamp,
                        sms_receive_dt timestamp,
                        status_code varchar(255),
                        terms_agreement varchar(255),
                        token_renew_dt timestamp,
                        created_dt timestamp,
                        updated_dt timestamp,
                        primary key (id)
);

create table member_detail (
                               id bigint generated by default as identity,
                               member_id bigint,
                               birth varchar(255),
                               email varchar(255),
                               gender_code varchar(255),
                               info_update_dt timestamp,
                               member_nm varchar(255),
                               mobile_number varchar(255),
                               nation_code varchar(255),
                               resident_number varchar(255),
                               tel varchar(255),
                               created_dt timestamp,
                               updated_dt timestamp,
                               primary key (id)
);

create table member_quit (
                             id bigint not null,
                             delete_dt timestamp,
                             quit_content varchar(255),
                             quit_reason_code varchar(255),
                             rejoin_dt timestamp,
                             created_dt timestamp,
                             updated_dt timestamp,
                             primary key (id)
);


alter table auth_code
    add constraint member_authCode
        foreign key (member_id)
            references member(id);

alter table member_detail
    add constraint member_memberDetail
        foreign key (member_id)
            references member(id);